version: '3'

services:
  backend:

    build:
      context: ./seprojbackend
      dockerfile: ./Dockerfile
    image: "sanjdoc/backend"
    ports:
      - "8888:2500"
  frontend:
    build:
      context: ./seprojfrontend
      dockerfile: ./Dockerfile
    image: "sanjdoc/frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
